# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/profiles/qemu-guest.nix")
    ];

  boot.initrd.availableKernelModules = [ "uhci_hcd" "ehci_pci" "ahci" "virtio_pci" "virtio_scsi" "sd_mod" "sr_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-intel" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-label/NIXROOT";
      fsType = "ext4";
      options = [  "noatime" "discard" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-label/NIXBOOT";
      fsType = "vfat";
      options = [  "noatime" "discard" ];
    };
    
  fileSystems."/nix" =
    { device = "/dev/disk/by-label/NIXSTORE";
      fsType = "f2fs";
      neededForBoot = true;
      options = [  "noatime" ];
    };

  fileSystems."/mnt/Backup1" = 
    { device = "/dev/disk/by-uuid/06caccf0-ec95-4abf-b0cc-2711033df259";
    fsType = "btrfs";     
    options = [ "nofail" "noatime" ];
    };

  fileSystems."/mnt/Backup2" = 
    { device = "/dev/disk/by-uuid/10a71a73-d9d6-4f03-bfa0-a1d1e1847322";
    fsType = "btrfs";     
    options = [ "nofail" "noatime" ];
    };

#  fileSystems."/mnt/Backup3" = 
#    { device = "/dev/disk/by-uuid/";
#    fsType = "btrfs";     
#    options = [ "nofail" "noatime"];
#    };

 swapDevices = [ {
    device = "/nix/var/swapfile";
    size = 1*1024;
  } ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp6s18.useDHCP = lib.mkDefault true;
}